### ISSUE TITLE
[Bug]: Course Description includes the course's name when it contains special characters.

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#173]
### What did you expect to happen?

The course description should start with the actual description for every course.

### What happened?

For courses with special characters in their name (parenthesis, slashes) the description includes the course name again which is repetitive and not consistent with other courses.

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Tasks
- [ ] Recognize that a course name without special characters is equal to the name at the start of the description
- [ ] Filter out the course name at the start of the course description
- [ ] Fix the course name (add in special characters)

**Comment by AbhiramTadepalli** [comment]
The description returned from the API always has the course name at the start. I filtered it out using the course name from the API. However, the API scrapes from CourseBook which does not properly display special characters for the course name, but does for the description.

**Comment by AbhiramTadepalli** [comment]
- [ ] a

**Comment by TyHil** [comment]
@AbhiramTadepalli what are some example courses for testing?

**Comment by AbhiramTadepalli** [comment]
GEOS 3300 - Missing parenthesis "()"
BUAN 6392 - missing forward-slash '/'
