### ISSUE TITLE
[Bug]: Search Result without grade distribution

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#181]
### What happened?

"John Cole" + "CS 2337" returns 1 result, without a grade distribution

### Tasks

- [ ] When does this occur?
    - [ ] How does Trends know that John Cole teaches this class if there is not grade distribution
- [ ] Why can I not find an instance of John Cole teaching cs2337!?
- [ ] Report the above in a comment here

### Related
https://github.com/UTDNebula/utd-trends/issues/180

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by George-Zhang5246** [comment]
John Cole taught CS 2337 in spring 2023. This is the only time he has taught the class.
I think we should just remove classes we don’t have data on to avoid confusion.

**Comment by AbhiramTadepalli** [comment]
do we know why there is no data for that class?

**Comment by AbhiramTadepalli** [comment]
@diyamehta1 a good first step is to see how/from where/why this course is being included

**Comment by TyHil** [comment]
@jpahm can you take a look at the API for me?

I can see [here](https://github.com/UTDNebula/api-tools/blob/develop/grade-data/23S.csv) that there is data for John Cole's one CS 2337 course but when I query the Nebula API it returns no data:

```
fetch(
  "https://api.utdnebula.com/grades/semester?prefix=CS&number=2337&first_name=John&last_name=Cole",
  {
    method: "GET",
    headers: {
      "x-api-key": "<API_KEY>",
      Accept: "application/json",
    },
  },
)
  .then((response) => response.json())
  .then((data) => console.log(data));
```
returns data `null`.

The same is true for PHYS 5V48 Aaron Smith which has data in [24S](https://github.com/UTDNebula/api-tools/blob/develop/grade-data/24S.csv) but returns null with https://api.utdnebula.com/grades/semester?prefix=PHYS&number=5V48&first_name=Aaron&last_name=Smith. Actually all of Aaron Smith: https://api.utdnebula.com/grades/semester?first_name=Aaron&last_name=Smith

**Comment by TyHil** [comment]
@jpahm looks like that fixed the data for Aaron Smith but I'm still not seeing anything for CS 2337 John Cole. Or CS 2337 Gordon Arnold when filtered to just 23S, when he taught the joint class with John Cole.

**Comment by jpahm** [comment]
@TyHil I've found the underlying issue; I'll be rolling out a fix for it shortly. On the bright side, it seems to be a relatively rare bug.

**Comment by TyHil** [comment]
@jpahm Oh great, give a ping here when deployed and I'll double check and close this issue.

**Comment by TyHil** [comment]
Resolved via an API fix

**Comment by George-Zhang5246** [comment]
The issue does not seem to be fixed, as seen in entries like these:
![IMG_2018](https://github.com/user-attachments/assets/fa65fbd7-1536-4a6f-a1e6-39c47d52286a)

replicate by searching ECS 3390

No RMP data but still shows the card for some reason.

**Comment by TyHil** [comment]
This seems to be a separate issue regarding RMP data instead of grade data but nonetheless

I believe this happens tho when a RMP profile exists for a professor but it has no reviews.

The data returned from RMP looks like this:
```
{
	"message": "success",
	"data": {
		"avgDifficulty": 0,
		"avgRating": 0,
		"department": "Engineering",
		"firstName": "Emily",
		"id": "VGVhY2hlci0yMTM0NjAw",
		"lastName": "Howsley",
		"legacyId": 2134600,
		"numRatings": 0,
		"ratingsDistribution": {
			"r1": 0,
			"r2": 0,
			"r3": 0,
			"r4": 0,
			"r5": 0,
			"total": 0
		},
		"school": {
			"id": "U2Nob29sLTEyNzM=",
			"name": "The University of Texas at Dallas"
		},
		"teacherRatingTags": [],
		"wouldTakeAgainPercent": -1
	}
}
```
So we could just do a check that `avgRating === 0` and set its state to `error` if that's the case.

This would be the easiest option. We could also add a separate check in the `singleProfInfo.tsx` component to keep the link to the professor profile displayed if the state is `error` but `legacyId` is still in the returned data.

**Comment by TyHil** [comment]
Covered in #288

**Comment by AbhiramTadepalli** [comment]
@TyHil how was this fixed?

**Comment by TyHil** [comment]
> @TyHil how was this fixed?

The grade issue was a bug in the API that has been fixed

**Comment by AbhiramTadepalli** [comment]
Sounds great!
