### ISSUE TITLE
[Feature Request] Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#266]
# Overview

Currently, system preferences dictate whether Trends is in light mode or dark mode

# Proposal
(a) Add a toggle to switch modes (b) remember user's preferences via cookies
By default, the toggle should be whatever system preferences is, but once the user selects a mode, cookies should remember upon subsequent site visits
## Tasks 
- [ ] Add a toggle to switch between light and dark mode
   - [ ] On first visit, use system preferences
- [ ] Remember user's preferences via cookies

**Comment by AbhiramTadepalli** [comment]
@iamwood suggested this 🙂
