### ISSUE TITLE
[Feature Request] Search Engine Optimization (SEO)

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#267]
# Overview

Describe the motivation behind your desired functionality.

How would you like the user experience for this feature to work?

# Proposal

There are a couple parts to this. First we need to find out what meta data we can customize for our site that SE's read. Then we need to identify good keywords to use when filling those out. Also sitemap. After that, let's try to get Trends to be #1 for different search queries (like UTD Galaxy, Orion, Coursebook, etc)

## Tasks

- [ ] What metadata can we customize for search engines? Comment it below
- [ ] Important keywords
- [ ] Fill out the meta tags
- [x] Finalize a sitemap (should be very simple imo)
- [ ] Incorporate keywords to put Trends at the top of tangentially-related search results

**Comment by AbhiramTadepalli** [comment]
https://www.google.com/search?q=utd+trends+site:utdnebula.com&sca_esv=2100fb941db67f3a&sxsrf=ADLYWIL3MU0wPovHPU1KMY6rrLjanRnZ5g:1730841586874&sa=X&ved=2ahUKEwiVxsqvj8aJAxXjLdAFHdUJFAIQrAN6BAgMEAE&biw=948&bih=724&dpr=1.25

for reference
